# Generated by Django 2.0.7 on 2019-12-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'goal',
            },
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('goal_id', models.CharField(max_length=11)),
                ('mealtype_id', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=225)),
                ('quantity', models.CharField(max_length=225)),
                ('day_time', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'meals',
            },
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'meal_type',
            },
        ),
        migrations.CreateModel(
            name='Supplements',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('goal_id', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=225)),
                ('day_time', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'supplements',
            },
        ),
    ]
