# Generated by Django 2.0.7 on 2020-01-14 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AIfitnesstrainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='goal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AIfitnesstrainer.Goal'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='mealtype_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AIfitnesstrainer.MealType'),
        ),
        migrations.AlterField(
            model_name='supplements',
            name='goal_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AIfitnesstrainer.Goal'),
        ),
    ]
