# Generated by Django 2.0.7 on 2020-01-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIfitnesstrainer', '0002_auto_20200114_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='name',
            new_name='g_name',
        ),
        migrations.RenameField(
            model_name='mealtype',
            old_name='name',
            new_name='mt_name',
        ),
    ]
