# Generated by Django 2.0.7 on 2020-01-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIfitnesstrainer', '0003_auto_20200114_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplements',
            name='id',
            field=models.AutoField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
