# Generated by Django 2.0.7 on 2020-01-15 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AIfitnesstrainer', '0004_auto_20200115_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeworkout',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('sets', models.IntegerField(max_length=11)),
                ('reps', models.IntegerField(max_length=11)),
                ('goal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AIfitnesstrainer.Goal')),
            ],
            options={
                'db_table': 'home_workout',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(max_length=11)),
                ('type', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=225)),
                ('height', models.IntegerField(max_length=11)),
                ('weight', models.IntegerField(max_length=11)),
                ('goal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AIfitnesstrainer.Goal')),
                ('mealtype_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AIfitnesstrainer.MealType')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
