# Generated by Django 2.0.7 on 2020-01-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIfitnesstrainer', '0005_homeworkout_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supplementtable',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
