# Generated by Django 2.0.7 on 2020-01-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIfitnesstrainer', '0006_auto_20200115_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='calories',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
