# Generated by Django 2.0.7 on 2020-01-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIfitnesstrainer', '0007_goal_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='goal_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mealtype_id',
        ),
    ]
